version: '3.4'

services:
  database:
    image: kartoza/postgis:10.0-2.4
    restart: always
  egl.sit.api:
    image: ${DOCKER_REGISTRY-}eglsitapi
    build:
      context: .
      dockerfile: src/backend/Egl.Sit.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__SitDbConnection=Host=database;Port=5432;Database=sit3;Username=sit;Password=123456;Persist Security Info=True
      - ConnectionStrings__EventStoreDbConnection=Host=database;Port=5432;Database=sit3;Username=sit;Password=123456;Persist Security Info=True
    ports:
      - "5001:80"
    depends_on:
      - database