version: '3.4'

services:
  database:
    environment:
      POSTGRES_USER : sit
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB : sit3
  egl.sit.api:
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    environment:
      - SIT_SEED=true